### ISSUE TITLE
Скачиваются превьюшки, но не изображения

### ISSUE THREAD

**Issue by iCloud** [Shrikimaru/vk_dialog_photos_dump_script#2]
Решил воспользоваться скриптом. Есть две проблемы:
1. Скачиваются превью изображений, но не полные их версии. 
2. Не подставляется расширение файла изображения.

**Comment by dokxpi** [comment]
_iCloud_, [https://github.com/dokxpi/VKIMImport](https://github.com/dokxpi/VKIMImport#vkimimport-boom-013)
